version: '3.9'
services:
  mongodb:
    image: mongo:4.4.6
    container_name: db_mongo
    networks:
      - my-rede
  alurabooks:
    image: aluradocker/alura-books:1.0
    container_name: alurabooks
    networks:
      - my-rede
    ports:
      - 3000:3000
    depends_on:
      - mongodb
networks:
  my-rede:
    driver: bridge
